server:
  servlet:
    context-path: /votacao

springdoc:
  swagger-ui:
    path: /public/swagger

logging:
  level:
    com.prata: ${LOG_LEVEL:DEBUG}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=votacao}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:852456}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 20
      maximumPoolSize: 200
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          default_schema: votacao

cloud:
  aws:
    credentials:
      accessKey: ${AWS_SNS_ACCESS_KEY:teste}
      secretKey: ${AWS_SNS_SECRET_KEY:teste}
    stack: false
    stack.auto: false
    region:
      auto: false
      static: ${AWS_SNS_REGION:us-east-1}
      use-default-aws-region-chain: true

aws:
  config:
    region: ${AWS_SNS_REGION:us-east-1}
    accesskey: ${AWS_SNS_ACCESS_KEY:teste}
    secretkey: ${AWS_SNS_SECRET_KEY:teste}
    endpointuri: ${AWS_SNS_ENDPOINT:http://localhost:4566}
    resultadoSessaoTopic: ${AWS_SNS_RESULTADO_SESSAO_TOPIC:resultado-sessao-topic}